name: Benchmark Full (Manual)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Proxifier:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: Proxifier
  Linux:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: Linux
  Apache:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: Apache
  Zookeeper:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: Zookeeper
  Mac:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: Mac
  HealthApp:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: HealthApp
  Hadoop:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: Hadoop
  OpenStack:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: OpenStack
  HPC:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: HPC
  OpenSSH:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: OpenSSH
  BGL:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: BGL
  Spark:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: Spark
  HDFS:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: HDFS
  Thunderbird:
    uses: ./.github/workflows/_benchmark-full.yml
    with:
      dataset: Thunderbird
